# file generated by setuptools-scm
# do not change, do not track in version control
from __future__ import annotations

__all__ = [
	"__version__",
	"__version_tuple__",
]

__version__: str
__version_tuple__: tuple[int | str, ...]

__version__ = "0.1.0"
__version_tuple__ = (0, 1, 0)
